### ISSUE TITLE
submitting a Figma link with your redesign

### ISSUE THREAD

**Issue by dotsvm** [appwrite-octernship/design-task#1]
Can anyone help me that where we have to submit the Figma link after completing the design?

**Comment by tessamero** [comment]
Creating a new branch
Making changes on the new branch to complete the project
Opening a Pull Request for review
Using GitHub Discussions to ask any relevant questions regarding the project

Use a readme.md file with the figma links as we will look for any file where you can add links

**Comment by dotsvm** [comment]
Ok thank you
